### ISSUE TITLE
URL's no longer work

### ISSUE THREAD

**Issue by lastraum** [dudik/twitch-m3u8#10]
Not sure if it's a limit issue with Twitch, the Graph, or something, but retrieving the .m3u8 link and trying to play that link directly no longer works. testing with www.hlsplayer.net and pasting any of the resolution links with video...

**Comment by dudik** [comment]
It doesn't work because of [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). Twitch doesn't allow requesting streams from hlsplayer.net. You will have to watch the stream through a local media player like mpv (tested a few minutes ago), VLC etc.
