### ISSUE TITLE
Documentation doesn't explain how to use the program to an average user.

### ISSUE THREAD

**Issue by ghost** [dudik/twitch-m3u8#12]
I look at this and I have no clue how to use it. Sure, I can download it just fine, but after that point I have no idea what to do next.

**Comment by dudik** [comment]
This is a library, not an application ready to be used. The [usage section](https://github.com/dudik/twitch-m3u8#usage) should be sufficient. If it isn't, you are probably looking for something like [streamlink](https://github.com/streamlink/streamlink).
