### ISSUE TITLE
The audio only quality is showing video

### ISSUE THREAD

**Issue by Zero3K** [dudik/twitch-m3u8#15]
*subject*

**Comment by Zero3K** [comment]
It's the same as 160p for some reason. Can it be fixed or not?

**Comment by Zero3K** [comment]
Well?

**Comment by dudik** [comment]
Can you give a specific example URL? Does it happen only with live streams, VODs, or both? I'm not able to reproduce.

**Comment by Zero3K** [comment]
It happens with Tardsplaya. I have no other way to test it.

**Comment by dudik** [comment]
The Tardsplaya repository you linked in your other issue doesn't seem to use this package. Thus I'm not able to help you.

**Comment by Zero3K** [comment]
It is. Please check https://github.com/Zero3K/Tardsplaya/commit/815ac838b80ee924ea86840bd7a8e575d4ec93d9.

**Comment by dudik** [comment]
It's not. It's using similar "code logic", but not the twitch-m3u8 npm package. I have nothing to do with Tardsplaya. I don't even use Pascal.
If you have a problem with the twitch-m3u8 npm package, I'll gladly help. But I'm not able to help with code from other repositories written by other people in languages that I don't understand. Sorry.
